### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bibitoo** [OpenCloudOS/nettrace#106]
nettrace/shared/bpf_utils.h:55:9: error: ‘BPF_FUNC_get_func_ret’ undeclared (first use in this function); did you mean ‘BPF_FUNC_get_func_ip’?
   55 |         BPF_FUNC_##name, NULL) == 1;
      |         ^~~~~~~~~

Ubuntu 22.04.2 LTS

**Comment by menglongdong** [comment]
你好，是基于docker编译的吗？建议基于docker来编译
