### ISSUE TITLE
docker编译失败

### ISSUE THREAD

**Issue by qpwo2468** [OpenCloudOS/nettrace#119]
下载了最新的imagedong/nettrace-build镜像，但是执行编译时，报错
![Dingtalk_20240919170249](https://github.com/user-attachments/assets/45162d80-fcac-4d21-93f2-4d9d267a5b39)

linux内核版本：4.19.60  x86_64
docker版本：4.2.1

**Comment by menglongdong** [comment]
看起来是你的这个docker镜像有问题，可以docker images看一下镜像是不是OK的

**Comment by qpwo2468** [comment]
这个镜像是从其他设备上拷贝过来的，刚才试了下，在下载的设备上可以正常编译，拷贝出来的镜像就不行了，多谢了

**Comment by qpwo2468** [comment]
编译成功，但是执行报错
![Dingtalk_20240919182843](https://github.com/user-attachments/assets/b37d95c9-8b2e-4219-9b87-153f459e4679)

**Comment by qpwo2468** [comment]
这里是完整的日志
[fail.log](https://github.com/user-attachments/files/17057627/fail.log)

**Comment by qpwo2468** [comment]
#113
