### ISSUE TITLE
does nettrace support Arm64 Linux?

### ISSUE THREAD

**Issue by deneschen** [OpenCloudOS/nettrace#14]
does nettrace support Arm64 Linux?

**Comment by xmmgithub** [comment]
> does nettrace support Arm64 Linux?

Yes, it support. The rpm/deb for arm is not provided in the releases, but you can compile it in a arm machine.

**Comment by xmmgithub** [comment]
Sorry, the arm64 compile fail before :/
But now, it can pass with this commit:

```
[support to compile for amr64 arch ](https://github.com/OpenCloudOS/nettrace/pull/24)
```
