### ISSUE TITLE
Can it support namespace？

### ISSUE THREAD

**Issue by gentoolovers** [OpenCloudOS/nettrace#16]

**Comment by xmmgithub** [comment]
你好，能简单描述一下你的场景吗？

**Comment by gentoolovers** [comment]
> 你好，能简单描述一下你的场景吗？

我的场景大概是这样的，我们会再服务器上创建多个docker， docker与宿主机机之间是通过veth peer
 + namespace 通信的。所以当我想用nettrace 跟踪docker内部的网络时，我需要进入对应的namespace执行nettrace命令，因为在对应的namespace里才能找到对应的接口。现在的情况是，当进入namespace执行nettrace命令时，直接报错了。

**Comment by xmmgithub** [comment]
> > 你好，能简单描述一下你的场景吗？
> 
> 我的场景大概是这样的，我们会再服务器上创建多个docker， docker与宿主机机之间是通过veth peer + namespace 通信的。所以当我想用nettrace 跟踪docker内部的网络时，我需要进入对应的namespace执行nettrace命令，因为在对应的namespace里才能找到对应的接口。现在的情况是，当进入namespace执行nettrace命令时，直接报错了。

你好，这个场景还是比较典型的。针对该场景，已规划到版本规划，预计下个版本完成功能支持。

**Comment by vsxen** [comment]
可以试下 https://gist.github.com/chendotjs/194768c411f15ecfec11e7235c435fa0

**Comment by xmmgithub** [comment]
> 可以试下 https://gist.github.com/chendotjs/194768c411f15ecfec11e7235c435fa0

这里进行namespace的获取和过滤的方式还是挺巧妙的，之前一直没有想到合适的方式，所以迟迟没有实现。感谢提醒！

**Comment by vsxen** [comment]
客气了，感谢你们的开源项目。
