### ISSUE TITLE
ubuntu installation failed

### ISSUE THREAD

**Issue by chiao666** [OpenCloudOS/nettrace#6]
The installation of multiple packages under ubuntu16.04 20.04 fails, and the droptrace compilation prompts that the current kernel is not supported, but the 5.4 and 5.18 kernels have been tried

**Comment by xmmgithub** [comment]
> The installation of multiple packages under ubuntu16.04 20.04 fails, and the droptrace compilation prompts that the current kernel is not supported, but the 5.4 and 5.18 kernels have been tried

Thanks for your feedback, I'll have a try on ubuntu 16.04 and 20.04.

**Comment by xmmgithub** [comment]
> The installation of multiple packages under ubuntu16.04 20.04 fails, and the droptrace compilation prompts that the current kernel is not supported, but the 5.4 and 5.18 kernels have been tried

Hello, I did some commits and I think it will be fine on ubuntu. The installation fails mainly caused by the version of clang, so you'd better to use clang10+. You can follow the README.md that I completed.

As for the unsupport of droptrace, I think it's because that the kernel is not new enough. After the commit "net: skb: move enum skb_drop_reason to standalone header file", I moved the enum skb_drop_reason from sk_buff.h to drop_reason.h, and the Makefile failed to find it. However, I made some adjust, and now it works on kernel5.18 that not new enough.

As for kernel5.4, I think the kernel doesn't support droptrace, unless you backported the 'drop reason' kernel feature.

BTW......哥们，你是南航的吗？我是你校友哇

**Comment by chiao666** [comment]
> > The installation of multiple packages under ubuntu16.04 20.04 fails, and the droptrace compilation prompts that the current kernel is not supported, but the 5.4 and 5.18 kernels have been tried
> 
> Hello, I did some commits and I think it will be fine on ubuntu. The installation fails mainly caused by the version of clang, so you'd better to use clang10+. You can follow the README.md that I completed.
> 
> As for the unsupport of droptrace, I think it's because that the kernel is not new enough. After the commit "net: skb: move enum skb_drop_reason to standalone header file", I moved the enum skb_drop_reason from sk_buff.h to drop_reason.h, and the Makefile failed to find it. However, I made some adjust, and now it works on kernel5.18 that not new enough.
> 
> As for kernel5.4, I think the kernel doesn't support droptrace, unless you backported the 'drop reason' kernel feature.
> 
> BTW......哥们，你是南航的吗？我是你校友哇

感谢测试！我是南航研二滴，老哥应该是学长吧，感谢测试！

**Comment by xmmgithub** [comment]
> > > The installation of multiple packages under ubuntu16.04 20.04 fails, and the droptrace compilation prompts that the current kernel is not supported, but the 5.4 and 5.18 kernels have been tried
> > 
> > 
> > Hello, I did some commits and I think it will be fine on ubuntu. The installation fails mainly caused by the version of clang, so you'd better to use clang10+. You can follow the README.md that I completed.
> > As for the unsupport of droptrace, I think it's because that the kernel is not new enough. After the commit "net: skb: move enum skb_drop_reason to standalone header file", I moved the enum skb_drop_reason from sk_buff.h to drop_reason.h, and the Makefile failed to find it. However, I made some adjust, and now it works on kernel5.18 that not new enough.
> > As for kernel5.4, I think the kernel doesn't support droptrace, unless you backported the 'drop reason' kernel feature.
> > BTW......哥们，你是南航的吗？我是你校友哇
> 
> 感谢测试！我是南航研二滴，老哥应该是学长吧，感谢测试！

哈哈，是的！我是19年毕业的机电学院的。没啥问题的话，我就关闭这个issue了哈~
