### ISSUE TITLE
一个带桥的路由器上捕捉icmp报文，为什么没有桥相关处理函数，是因为桥不是内核默认模块吗？

### ISSUE THREAD

**Issue by stevetao74** [OpenCloudOS/nettrace#65]

**Comment by xmmgithub** [comment]
你说的是网桥（bridge）设备吗？为了降低系统的开销，nettrace里的一些跟踪函数默认是禁止了的，其中就包括bridge。可以在命令行中使用-t all来强制跟踪所有支持的函数。也可以使用-t bridge来单独跟踪网桥的处理函数。

PS：目前配置文件（trace.yaml）中网桥的处理函数比较少，只有下面四个netfilter相关的。你可以按照自己的需要增加。
<img width="371" alt="图片" src="https://github.com/OpenCloudOS/nettrace/assets/16660844/0c086acd-483e-4045-928b-ac642ab966c5">
