### ISSUE TITLE
可否输出时间戳

### ISSUE THREAD

**Issue by super2346** [OpenCloudOS/nettrace#7]
![image](https://user-images.githubusercontent.com/30429475/189091562-1f37c92e-ebbc-47b2-8756-317be4a85c8a.png)
如图红框输出看着像一个相对的时间戳，可否有转换成绝对的时间戳的方法

**Comment by xmmgithub** [comment]
> ![image](https://user-images.githubusercontent.com/30429475/189091562-1f37c92e-ebbc-47b2-8756-317be4a85c8a.png) 如图红框输出看着像一个相对的时间戳，可否有转换成绝对的时间戳的方法

你好，可以的，已列入到当前版本规划

**Comment by xmmgithub** [comment]
已完成功能支持，效果如下：

<img width="343" alt="图片" src="https://user-images.githubusercontent.com/16660844/197345828-729fcb51-8cba-4c0a-b6d3-52e956136dad.png">

**Comment by super2346** [comment]
赞👍🏻，辛苦了
