### ISSUE TITLE
x86_64 最新的release 的nettrace 启动后一直卡着，内核版本6.1.13

### ISSUE THREAD

**Issue by hezhiye** [OpenCloudOS/nettrace#77]
uname -ra
Linux localhost 6.1.13-android_x86_64 #1 SMP PREEMPT Sun Nov 12 19:47:32 CST 2023 x86_64 Toybox

130|HYSS:/data/local/tmp # ./nettrace -p icmp --debug                                                                                                                                                
DEBUG: command: mount | grep debugfs, status:0
DEBUG: command: cat /sys/kernel/debug/tracing/events/skb/kfree_skb/format 2>/dev/null | grep NOT_SPECIFIED, status:0
DEBUG: trace name=tcp_ack_probe, prog=__trace_tcp_ack_probe is made invalid for: sock or sk mode
DEBUG: trace name=tcp_probe_timer, prog=__trace_tcp_probe_timer is made invalid for: sock or sk mode
DEBUG: trace name=tcp_send_probe0, prog=__trace_tcp_send_probe0 is made invalid for: sock or sk mode
DEBUG: trace name=__tcp_transmit_skb, prog=__trace___tcp_transmit_skb is made invalid for: sock or sk mode
DEBUG: trace name=tcp_sendmsg_locked, prog=__trace_tcp_sendmsg_locked is made invalid for: sock or sk mode
DEBUG: trace name=__tcp_push_pending_frames, prog=__trace___tcp_push_pending_frames is made invalid for: sock or sk mode
DEBUG: trace name=inet_listen, prog=__trace_inet_listen is made invalid for: sock or sk mode
DEBUG: trace name=tcp_v4_destroy_sock, prog=__trace_tcp_v4_destroy_sock is made invalid for: sock or sk mode
DEBUG: trace name=tcp_close, prog=__trace_tcp_close is made invalid for: sock or sk mode
DEBUG: trace name=tcp_write_timer_handler, prog=__trace_tcp_write_timer_handler is made invalid for: sock or sk mode
DEBUG: trace name=tcp_retransmit_timer, prog=__trace_tcp_retransmit_timer is made invalid for: sock or sk mode
DEBUG: trace name=tcp_enter_recovery, prog=__trace_tcp_enter_recovery is made invalid for: sock or sk mode
DEBUG: trace name=tcp_enter_loss, prog=__trace_tcp_enter_loss is made invalid for: sock or sk mode
DEBUG: trace name=tcp_try_keep_open, prog=__trace_tcp_try_keep_open is made invalid for: sock or sk mode
DEBUG: trace name=tcp_enter_cwr, prog=__trace_tcp_enter_cwr is made invalid for: sock or sk mode
DEBUG: trace name=tcp_fastretrans_alert, prog=__trace_tcp_fastretrans_alert is made invalid for: sock or sk mode
DEBUG: trace name=tcp_rearm_rto, prog=__trace_tcp_rearm_rto is made invalid for: sock or sk mode
DEBUG: trace name=tcp_event_new_data_sent, prog=__trace_tcp_event_new_data_sent is made invalid for: sock or sk mode
DEBUG: trace name=tcp_schedule_loss_probe, prog=__trace_tcp_schedule_loss_probe is made invalid for: sock or sk mode
DEBUG: command: verlte() { [ "$1" = "$2" ] && echo 0 && return; [ "$1" = "$(/bin/echo -e "$1\n$2" | sort -V | head -n1)" ] && echo -1 && return; echo 1; }; [ ! $(verlte "$(uname -r)" "5.4") -eq -1 ], status:0
DEBUG: command: verlte() { [ "$1" = "$2" ] && echo 0 && return; [ "$1" = "$(/bin/echo -e "$1\n$2" | sort -V | head -n1)" ] && echo -1 && return; echo 1; }; [ $(verlte "$(uname -r)" "5.16") -eq -1 ], status:1
DEBUG: trace name=ipt_do_table, prog=__trace_ipt_do_table_legacy is made invalid for: cond
DEBUG: begin to resolve kernel symbol...
kernel function bond_dev_queue_xmit not founded, skipped
DEBUG: trace name=bond_dev_queue_xmit, prog=__trace_bond_dev_queue_xmit is made invalid for: not found
kernel function nft_do_chain not founded, skipped
DEBUG: trace name=nft_do_chain, prog=__trace_nft_do_chain is made invalid for: not found
kernel function tcp_in_window not founded, skipped
DEBUG: trace name=tcp_in_window, prog=__trace_tcp_in_window is made invalid for: not found
kernel function ip_finish_output_gso not founded, skipped
DEBUG: trace name=ip_finish_output_gso, prog=__trace_ip_finish_output_gso is made invalid for: not found
kernel function xfrm_output_gso not founded, skipped
DEBUG: trace name=xfrm_output_gso, prog=__trace_xfrm_output_gso is made invalid for: not found
kernel function xfrm4_transport_output not founded, skipped
DEBUG: trace name=xfrm4_transport_output, prog=__trace_xfrm4_transport_output is made invalid for: not found
kernel function xfrm4_prepare_output not founded, skipped
DEBUG: trace name=xfrm4_prepare_output, prog=__trace_xfrm4_prepare_output is made invalid for: not found
kernel function xfrm4_transport_input not founded, skipped
DEBUG: trace name=xfrm4_transport_input, prog=__trace_xfrm4_transport_input is made invalid for: not found
kernel function ah_output not founded, skipped
DEBUG: trace name=ah_output, prog=__trace_ah_output is made invalid for: not found
kernel function ah_input not founded, skipped
DEBUG: trace name=ah_input, prog=__trace_ah_input is made invalid for: not found
kernel function ip_route_input_slow not founded, skipped
DEBUG: trace name=ip_route_input_slow, prog=__trace_ip_route_input_slow is made invalid for: not found
DEBUG: __ping_queue_rcv_skb.__UNIQUE_ID_ddebug593 is made manual attach
DEBUG: finished to resolve kernel symbol
DEBUG: kernel feature probe begin
DEBUG: kernel feature probe end
DEBUG: backup: valid prog for __netif_receive_skb_core is __trace___netif_receive_skb_core_pskb
DEBUG: trace name=__netif_receive_skb_core, prog=__trace___netif_receive_skb_core is made invalid for: backup
DEBUG: backup: valid prog for ipt_do_table is __trace_ipt_do_table
following traces are enabled and valid:
        tracepoint: napi_gro_receive_entry, prog: __trace_napi_gro_receive_entry
        kprobe: dev_gro_receive, prog: __trace_dev_gro_receive
        kprobe: enqueue_to_backlog, prog: __trace_enqueue_to_backlog
        kprobe: netif_receive_generic_xdp, prog: __trace_netif_receive_generic_xdp
        kprobe: xdp_do_generic_redirect, prog: __trace_xdp_do_generic_redirect
        kprobe: __netif_receive_skb_core, prog: __trace___netif_receive_skb_core_pskb
        kprobe: __dev_queue_xmit, prog: __trace___dev_queue_xmit
        kprobe: dev_hard_start_xmit, prog: __trace_dev_hard_start_xmit
        kprobe: tcf_classify, prog: __trace_tcf_classify
        kprobe: cls_bpf_classify, prog: __trace_cls_bpf_classify
        kprobe: tcf_bpf_act, prog: __trace_tcf_bpf_act
        kprobe: pfifo_enqueue, prog: __trace_pfifo_enqueue
        kprobe: pfifo_fast_enqueue, prog: __trace_pfifo_fast_enqueue
        kprobe: sch_direct_xmit, prog: __trace_sch_direct_xmit
        kprobe: arp_rcv, prog: __trace_arp_rcv
        kprobe: arp_process, prog: __trace_arp_process
        kprobe: packet_rcv, prog: __trace_packet_rcv
        kprobe: tpacket_rcv, prog: __trace_tpacket_rcv
        kprobe: packet_direct_xmit, prog: __trace_packet_direct_xmit
        kprobe: nf_nat_manip_pkt, prog: __trace_nf_nat_manip_pkt
        kprobe: nf_hook_slow, prog: __trace_nf_hook_slow
        kprobe: ipt_do_table, prog: __trace_ipt_do_table
        kprobe: ip_rcv, prog: __trace_ip_rcv
        kprobe: ip_rcv_core, prog: __trace_ip_rcv_core
        kprobe: ip_rcv_finish, prog: __trace_ip_rcv_finish
        kprobe: ip_local_deliver, prog: __trace_ip_local_deliver
        kprobe: ip_local_deliver_finish, prog: __trace_ip_local_deliver_finish
        kprobe: ip_forward, prog: __trace_ip_forward
        kprobe: ip_forward_finish, prog: __trace_ip_forward_finish
        kprobe: ip6_forward, prog: __trace_ip6_forward
        kprobe: ip6_rcv_finish, prog: __trace_ip6_rcv_finish
        kprobe: ip6_rcv_core, prog: __trace_ip6_rcv_core
        kprobe: ipv6_rcv, prog: __trace_ipv6_rcv
        kprobe: ip_output, prog: __trace_ip_output
        kprobe: ip_finish_output, prog: __trace_ip_finish_output
        kprobe: ip_finish_output2, prog: __trace_ip_finish_output2
        kprobe: ip6_output, prog: __trace_ip6_output
        kprobe: ip6_finish_output, prog: __trace_ip6_finish_output
        kprobe: ip6_finish_output2, prog: __trace_ip6_finish_output2
        kprobe: ip6_send_skb, prog: __trace_ip6_send_skb
        kprobe: ip6_local_out, prog: __trace_ip6_local_out
        kprobe: xfrm4_output, prog: __trace_xfrm4_output
        kprobe: xfrm_output, prog: __trace_xfrm_output
        kprobe: xfrm_output2, prog: __trace_xfrm_output2
        kprobe: xfrm_output_resume, prog: __trace_xfrm_output_resume
        kprobe: xfrm4_policy_check, prog: __trace_xfrm4_policy_check
        kprobe: xfrm4_rcv, prog: __trace_xfrm4_rcv
        kprobe: xfrm_input, prog: __trace_xfrm_input
        kprobe: esp_output, prog: __trace_esp_output
        kprobe: esp_output_tail, prog: __trace_esp_output_tail
        kprobe: esp_input, prog: __trace_esp_input
        kprobe: fib_validate_source, prog: __trace_fib_validate_source
        kprobe: tcp_v4_rcv, prog: __trace_tcp_v4_rcv
        kprobe: tcp_v6_rcv, prog: __trace_tcp_v6_rcv
        kprobe: tcp_filter, prog: __trace_tcp_filter
        kprobe: tcp_child_process, prog: __trace_tcp_child_process
        kprobe: tcp_v4_send_reset, prog: __trace_tcp_v4_send_reset
        kprobe: tcp_v6_send_reset, prog: __trace_tcp_v6_send_reset
        kprobe: tcp_v4_do_rcv, prog: __trace_tcp_v4_do_rcv
        kprobe: tcp_v6_do_rcv, prog: __trace_tcp_v6_do_rcv
        kprobe: tcp_rcv_established, prog: __trace_tcp_rcv_established
        kprobe: tcp_rcv_state_process, prog: __trace_tcp_rcv_state_process
        kprobe: tcp_queue_rcv, prog: __trace_tcp_queue_rcv
        kprobe: tcp_ack, prog: __trace_tcp_ack
        kprobe: __inet_lookup_listener, prog: __trace___inet_lookup_listener
        kprobe: inet6_lookup_listener, prog: __trace_inet6_lookup_listener
        kprobe: udp_rcv, prog: __trace_udp_rcv
        kprobe: udp_unicast_rcv_skb, prog: __trace_udp_unicast_rcv_skb
        kprobe: udp_queue_rcv_skb, prog: __trace_udp_queue_rcv_skb
        kprobe: xfrm4_udp_encap_rcv, prog: __trace_xfrm4_udp_encap_rcv
        kprobe: xfrm4_rcv_encap, prog: __trace_xfrm4_rcv_encap
        kprobe: __udp_queue_rcv_skb, prog: __trace___udp_queue_rcv_skb
        kprobe: __udp_enqueue_schedule_skb, prog: __trace___udp_enqueue_schedule_skb
        kprobe: icmp_rcv, prog: __trace_icmp_rcv
        kprobe: icmp_echo, prog: __trace_icmp_echo
        kprobe: icmp_reply, prog: __trace_icmp_reply
        kprobe: icmpv6_rcv, prog: __trace_icmpv6_rcv
        kprobe: icmpv6_echo_reply, prog: __trace_icmpv6_echo_reply
        kprobe: ping_rcv, prog: __trace_ping_rcv
        kprobe: __ping_queue_rcv_skb.__UNIQUE_ID_ddebug593, prog: __trace___ping_queue_rcv_skb
        kprobe: ping_queue_rcv_skb, prog: __trace_ping_queue_rcv_skb
        kprobe: ping_lookup, prog: __trace_ping_lookup
        kprobe: __kfree_skb, prog: __trace___kfree_skb
        kprobe/kretprobe: skb_clone, prog: __trace_skb_clone
        tracepoint: consume_skb, prog: __trace_consume_skb
        tracepoint: kfree_skb, prog: __trace_kfree_skb
DEBUG: eBPF is opened successfully
DEBUG: prog: __trace_dev_gro_receive is made no-autoload
DEBUG: prog: __trace_enqueue_to_backlog is made no-autoload
DEBUG: prog: __trace_netif_receive_generic_xdp is made no-autoload
DEBUG: prog: __trace_xdp_do_generic_redirect is made no-autoload
DEBUG: prog: __trace___netif_receive_skb_core is made no-autoload
DEBUG: prog: __trace___netif_receive_skb_core is made no-autoload
DEBUG: prog: __trace___netif_receive_skb_core_pskb is made no-autoload
DEBUG: prog: __trace___dev_queue_xmit is made no-autoload
DEBUG: prog: __trace_dev_hard_start_xmit is made no-autoload
DEBUG: prog: __trace_tcf_classify is made no-autoload
DEBUG: prog: __trace_cls_bpf_classify is made no-autoload
DEBUG: prog: __trace_tcf_bpf_act is made no-autoload
DEBUG: prog: __trace_pfifo_enqueue is made no-autoload
DEBUG: prog: __trace_pfifo_fast_enqueue is made no-autoload
DEBUG: prog: __trace_sch_direct_xmit is made no-autoload
DEBUG: prog: __trace_ipvlan_queue_xmit is made no-autoload
DEBUG: prog: __trace_ipvlan_queue_xmit is made no-autoload
DEBUG: prog: __trace_ipvlan_handle_frame is made no-autoload
DEBUG: prog: __trace_ipvlan_handle_frame is made no-autoload
DEBUG: prog: __trace_ipvlan_rcv_frame is made no-autoload
DEBUG: prog: __trace_ipvlan_rcv_frame is made no-autoload
DEBUG: prog: __trace_ipvlan_xmit_mode_l3 is made no-autoload
DEBUG: prog: __trace_ipvlan_xmit_mode_l3 is made no-autoload
DEBUG: prog: __trace_ipvlan_process_v4_outbound is made no-autoload
DEBUG: prog: __trace_ipvlan_process_v4_outbound is made no-autoload
DEBUG: prog: __trace_br_nf_pre_routing is made no-autoload
DEBUG: prog: __trace_br_nf_pre_routing is made no-autoload
DEBUG: prog: __trace_br_nf_forward_ip is made no-autoload
DEBUG: prog: __trace_br_nf_forward_ip is made no-autoload
DEBUG: prog: __trace_br_nf_forward_arp is made no-autoload
DEBUG: prog: __trace_br_nf_forward_arp is made no-autoload
DEBUG: prog: __trace_br_nf_post_routing is made no-autoload
DEBUG: prog: __trace_br_nf_post_routing is made no-autoload
DEBUG: prog: __trace_arp_rcv is made no-autoload
DEBUG: prog: __trace_arp_process is made no-autoload
DEBUG: prog: __trace_bond_dev_queue_xmit is made no-autoload
DEBUG: prog: __trace_bond_dev_queue_xmit is made no-autoload
DEBUG: prog: __trace_packet_rcv is made no-autoload
DEBUG: prog: __trace_tpacket_rcv is made no-autoload
DEBUG: prog: __trace_packet_direct_xmit is made no-autoload
DEBUG: prog: __trace_nft_do_chain is made no-autoload
DEBUG: prog: __trace_nft_do_chain is made no-autoload
DEBUG: prog: __trace_nf_nat_manip_pkt is made no-autoload
DEBUG: prog: __trace_nf_hook_slow is made no-autoload
DEBUG: prog: __trace_ipt_do_table is made no-autoload
DEBUG: prog: __trace_ipt_do_table_legacy is made no-autoload
DEBUG: prog: __trace_ipt_do_table_legacy is made no-autoload
DEBUG: prog: __trace_ipv4_confirm is made no-autoload
DEBUG: prog: __trace_ipv4_confirm is made no-autoload
DEBUG: prog: __trace_nf_confirm is made no-autoload
DEBUG: prog: __trace_nf_confirm is made no-autoload
DEBUG: prog: __trace_ipv4_conntrack_in is made no-autoload
DEBUG: prog: __trace_ipv4_conntrack_in is made no-autoload
DEBUG: prog: __trace_nf_conntrack_in is made no-autoload
DEBUG: prog: __trace_nf_conntrack_in is made no-autoload
DEBUG: prog: __trace_ipv4_pkt_to_tuple is made no-autoload
DEBUG: prog: __trace_ipv4_pkt_to_tuple is made no-autoload
DEBUG: prog: __trace_tcp_new is made no-autoload
DEBUG: prog: __trace_tcp_new is made no-autoload
DEBUG: prog: __trace_tcp_pkt_to_tuple is made no-autoload
DEBUG: prog: __trace_tcp_pkt_to_tuple is made no-autoload
DEBUG: prog: __trace_resolve_normal_ct is made no-autoload
DEBUG: prog: __trace_resolve_normal_ct is made no-autoload
DEBUG: prog: __trace_tcp_packet is made no-autoload
DEBUG: prog: __trace_tcp_packet is made no-autoload
DEBUG: prog: __trace_tcp_in_window is made no-autoload
DEBUG: prog: __trace_tcp_in_window is made no-autoload
DEBUG: prog: __trace___nf_ct_refresh_acct is made no-autoload
DEBUG: prog: __trace___nf_ct_refresh_acct is made no-autoload
DEBUG: prog: __trace_ip_rcv is made no-autoload
DEBUG: prog: __trace_ip_rcv_core is made no-autoload
DEBUG: prog: __trace_ip_rcv_finish is made no-autoload
DEBUG: prog: __trace_ip_local_deliver is made no-autoload
DEBUG: prog: __trace_ip_local_deliver_finish is made no-autoload
DEBUG: prog: __trace_ip_forward is made no-autoload
DEBUG: prog: __trace_ip_forward_finish is made no-autoload
DEBUG: prog: __trace_ip6_forward is made no-autoload
DEBUG: prog: __trace_ip6_rcv_finish is made no-autoload
DEBUG: prog: __trace_ip6_rcv_core is made no-autoload
DEBUG: prog: __trace_ipv6_rcv is made no-autoload
DEBUG: prog: __trace_ip_output is made no-autoload
DEBUG: prog: __trace_ip_finish_output is made no-autoload
DEBUG: prog: __trace_ip_finish_output_gso is made no-autoload
DEBUG: prog: __trace_ip_finish_output_gso is made no-autoload
DEBUG: prog: __trace_ip_finish_output2 is made no-autoload
DEBUG: prog: __trace_ip6_output is made no-autoload
DEBUG: prog: __trace_ip6_finish_output is made no-autoload
DEBUG: prog: __trace_ip6_finish_output2 is made no-autoload
DEBUG: prog: __trace_ip6_send_skb is made no-autoload
DEBUG: prog: __trace_ip6_local_out is made no-autoload
DEBUG: prog: __trace_xfrm4_output is made no-autoload
DEBUG: prog: __trace_xfrm_output is made no-autoload
DEBUG: prog: __trace_xfrm_output2 is made no-autoload
DEBUG: prog: __trace_xfrm_output_gso is made no-autoload
DEBUG: prog: __trace_xfrm_output_gso is made no-autoload
DEBUG: prog: __trace_xfrm_output_resume is made no-autoload
DEBUG: prog: __trace_xfrm4_transport_output is made no-autoload
DEBUG: prog: __trace_xfrm4_transport_output is made no-autoload
DEBUG: prog: __trace_xfrm4_prepare_output is made no-autoload
DEBUG: prog: __trace_xfrm4_prepare_output is made no-autoload
DEBUG: prog: __trace_xfrm4_policy_check is made no-autoload
DEBUG: prog: __trace_xfrm4_rcv is made no-autoload
DEBUG: prog: __trace_xfrm_input is made no-autoload
DEBUG: prog: __trace_xfrm4_transport_input is made no-autoload
DEBUG: prog: __trace_xfrm4_transport_input is made no-autoload
DEBUG: prog: __trace_ah_output is made no-autoload
DEBUG: prog: __trace_ah_output is made no-autoload
DEBUG: prog: __trace_esp_output is made no-autoload
DEBUG: prog: __trace_esp_output_tail is made no-autoload
DEBUG: prog: __trace_ah_input is made no-autoload
DEBUG: prog: __trace_ah_input is made no-autoload
DEBUG: prog: __trace_esp_input is made no-autoload
DEBUG: prog: __trace_fib_validate_source is made no-autoload
DEBUG: prog: __trace_ip_route_input_slow is made no-autoload
DEBUG: prog: __trace_ip_route_input_slow is made no-autoload
DEBUG: prog: __trace_tcp_v4_rcv is made no-autoload
DEBUG: prog: __trace_tcp_v6_rcv is made no-autoload
DEBUG: prog: __trace_tcp_filter is made no-autoload
DEBUG: prog: __trace_tcp_child_process is made no-autoload
DEBUG: prog: __trace_tcp_v4_send_reset is made no-autoload
DEBUG: prog: __trace_tcp_v6_send_reset is made no-autoload
DEBUG: prog: __trace_tcp_v4_do_rcv is made no-autoload
DEBUG: prog: __trace_tcp_v6_do_rcv is made no-autoload
DEBUG: prog: __trace_tcp_rcv_established is made no-autoload
DEBUG: prog: __trace_tcp_rcv_state_process is made no-autoload
DEBUG: prog: __trace_tcp_queue_rcv is made no-autoload
DEBUG: prog: __trace_tcp_ack_probe is made no-autoload
DEBUG: prog: __trace_tcp_ack_probe is made no-autoload
DEBUG: prog: __trace_tcp_ack is made no-autoload
DEBUG: prog: __trace_tcp_probe_timer is made no-autoload
DEBUG: prog: __trace_tcp_probe_timer is made no-autoload
DEBUG: prog: __trace_tcp_send_probe0 is made no-autoload
DEBUG: prog: __trace_tcp_send_probe0 is made no-autoload
DEBUG: prog: __trace___inet_lookup_listener is made no-autoload
DEBUG: prog: __trace_inet6_lookup_listener is made no-autoload
DEBUG: prog: __trace___tcp_transmit_skb is made no-autoload
DEBUG: prog: __trace___tcp_transmit_skb is made no-autoload
DEBUG: prog: __trace_tcp_sendmsg_locked is made no-autoload
DEBUG: prog: __trace_tcp_sendmsg_locked is made no-autoload
DEBUG: prog: __trace___tcp_push_pending_frames is made no-autoload
DEBUG: prog: __trace___tcp_push_pending_frames is made no-autoload
DEBUG: prog: __trace_udp_rcv is made no-autoload
DEBUG: prog: __trace_udp_unicast_rcv_skb is made no-autoload
DEBUG: prog: __trace_udp_queue_rcv_skb is made no-autoload
DEBUG: prog: __trace_xfrm4_udp_encap_rcv is made no-autoload
DEBUG: prog: __trace_xfrm4_rcv_encap is made no-autoload
DEBUG: prog: __trace___udp_queue_rcv_skb is made no-autoload
DEBUG: prog: __trace___udp_enqueue_schedule_skb is made no-autoload
DEBUG: prog: __trace_icmp_rcv is made no-autoload
DEBUG: prog: __trace_icmp_echo is made no-autoload
DEBUG: prog: __trace_icmp_reply is made no-autoload
DEBUG: prog: __trace_icmpv6_rcv is made no-autoload
DEBUG: prog: __trace_icmpv6_echo_reply is made no-autoload
DEBUG: prog: __trace_ping_rcv is made no-autoload
DEBUG: prog: __trace___ping_queue_rcv_skb is made no-autoload
DEBUG: prog: __trace_ping_queue_rcv_skb is made no-autoload
DEBUG: prog: __trace_ping_lookup is made no-autoload
DEBUG: prog: __trace_inet_listen is made no-autoload
DEBUG: prog: __trace_inet_listen is made no-autoload
DEBUG: prog: __trace_tcp_v4_destroy_sock is made no-autoload
DEBUG: prog: __trace_tcp_v4_destroy_sock is made no-autoload
DEBUG: prog: __trace_tcp_close is made no-autoload
DEBUG: prog: __trace_tcp_close is made no-autoload
DEBUG: prog: __trace_tcp_write_timer_handler is made no-autoload
DEBUG: prog: __trace_tcp_write_timer_handler is made no-autoload
DEBUG: prog: __trace_tcp_retransmit_timer is made no-autoload
DEBUG: prog: __trace_tcp_retransmit_timer is made no-autoload
DEBUG: prog: __trace_tcp_enter_recovery is made no-autoload
DEBUG: prog: __trace_tcp_enter_recovery is made no-autoload
DEBUG: prog: __trace_tcp_enter_loss is made no-autoload
DEBUG: prog: __trace_tcp_enter_loss is made no-autoload
DEBUG: prog: __trace_tcp_try_keep_open is made no-autoload
DEBUG: prog: __trace_tcp_try_keep_open is made no-autoload
DEBUG: prog: __trace_tcp_enter_cwr is made no-autoload
DEBUG: prog: __trace_tcp_enter_cwr is made no-autoload
DEBUG: prog: __trace_tcp_fastretrans_alert is made no-autoload
DEBUG: prog: __trace_tcp_fastretrans_alert is made no-autoload
DEBUG: prog: __trace_tcp_rearm_rto is made no-autoload
DEBUG: prog: __trace_tcp_rearm_rto is made no-autoload
DEBUG: prog: __trace_tcp_event_new_data_sent is made no-autoload
DEBUG: prog: __trace_tcp_event_new_data_sent is made no-autoload
DEBUG: prog: __trace_tcp_schedule_loss_probe is made no-autoload
DEBUG: prog: __trace_tcp_schedule_loss_probe is made no-autoload
DEBUG: prog: __trace___kfree_skb is made no-autoload

**Comment by hezhiye** [comment]
等了好几分钟才出现接下去的
DEBUG: eBPF is loaded successfully
DEBUG: begin to attach eBPF program...
libbpf: prog '__trace___ping_queue_rcv_skb': failed to create kprobe '__ping_queue_rcv_skb.__UNIQUE_ID_ddebug593+0x0' perf event: Invalid argument
retring to attach in legacy mode, prog=__trace___ping_queue_rcv_skb, func=__ping_queue_rcv_skb.__UNIQUE_ID_ddebug593
DEBUG: command: (echo 'p:__ping_queue_rcv_skb___UNIQUE_ID_ddebug593 __ping_queue_rcv_skb.__UNIQUE_ID_ddebug593' >> /sys/kernel/debug/tracing/kprobe_events) 2>&1, status:1
WARN: failed to create kprobe: __ping_queue_rcv_skb___UNIQUE_ID_ddebug593
ERROR: failed to manually attach program prog=__trace___ping_queue_rcv_skb, func=__ping_queue_rcv_skb.__UNIQUE_ID_ddebug593
DEBUG: eBPF program attached successfully

**Comment by hezhiye** [comment]
输入nettrace -p udp还出现段错误

DEBUG: create entry: 1b927c0, ffff8f724041ae00, size: 108
DEBUG: fake ctx alloc: 1ba14e0, ffff8f724041ae00
DEBUG: tp found for ip6_send_skb(ffff8f724041ae00), ctx:1bec830:1
DEBUG: create entry: 1d28860, ffff8f724041ae00, size: 108
DEBUG: tp found for ip6_local_out(ffff8f724041ae00), ctx:1bec830:1
DEBUG: create entry: 1d28950, ffff8f724041ae00, size: 132
DEBUG: tp found for nf_hook_slow(ffff8f724041ae00), ctx:1bec830:1





Segmentation fault 
139|HY11:/data/local/tmp # 
139|HY11:/data/local/tmp #

**Comment by xmmgithub** [comment]
感谢反馈，我先分析一下

**Comment by xmmgithub** [comment]
麻烦提供一下你用到的内核config,我来本地复现测试一下（我这边的内核配置没能复现出来问题）

**Comment by hezhiye** [comment]
[kernel-config.zip](https://github.com/OpenCloudOS/nettrace/files/13423911/kernel-config.zip)

**Comment by hezhiye** [comment]
如上这个是

**Comment by xmmgithub** [comment]
使用这个配置编译出来的内核没有能复现出来上面的问题。nettrace加载慢的问题，可以尝试只启用部分tracer，例如对于icmp，可以指定-t link,icmp,ip。后面我也会针对这块尝试使用高版本的一些特性进行优化。

对于UDP报段错误的问题，我这边没能复现，暂时没有排查思路。

**Comment by hezhiye** [comment]
我这边也是偶现
